// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.redcap.hashdefine.domain;

import com.redcap.hashdefine.domain.LogMessage;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LogMessage_Roo_Configurable {
    
    declare @type: LogMessage: @Configurable;
    
}
